{
	"001" : [
		{
			"vid" : "2016001001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016001a.jpg",
			"title" : "一分钟懒人运动01",
			"subtitle" : "洛希陪你做 再也找不到不减肥的理由了",
			"duration" : "00:53",
			"tags" : ["洛希","懒人健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016001001.mp4",
			"content" : "一分钟，能做什么事情呢？也许你一分钟都还没有思考完就已经过去了，是不是觉得很浪费？《一分钟懒人运动 洛希陪你做》而我们这档节目就是专供给懒人参考的，一分钟也可以轻松瘦身，你再也没理由说自己没时间减肥了。"
		},
		{
			"vid" : "2016001002",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016001b.jpg",
			"title" : "一分钟懒人运动02",
			"subtitle" : "洛希陪你做 再也找不到不减肥的理由了",
			"duration" : "00:54",
			"tags" : ["洛希","懒人健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身2",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016001002.mp4",
			"content" : "一分钟，能做什么事情呢？也许你一分钟都还没有思考完就已经过去了，是不是觉得很浪费？《一分钟懒人运动 洛希陪你做》而我们这档节目就是专供给懒人参考的，一分钟也可以轻松瘦身，你再也没理由说自己没时间减肥了。"
		},
		{
			"vid" : "2016001003",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016001c.jpg",
			"title" : "一分钟懒人运动03",
			"subtitle" : "洛希陪你做 再也找不到不减肥的理由了",
			"duration" : "00:53",
			"tags" : ["洛希","懒人健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身3",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016001003.mp4",
			"content" : "一分钟，能做什么事情呢？也许你一分钟都还没有思考完就已经过去了，是不是觉得很浪费？《一分钟懒人运动 洛希陪你做》而我们这档节目就是专供给懒人参考的，一分钟也可以轻松瘦身，你再也没理由说自己没时间减肥了。"
		}],
	"002" : [{
			"vid" : "2016002001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016002a.jpg",
			"title" : "办公室女神养成记01",
			"subtitle" : "跟着那虹在办公室运动起来",
			"duration" : "02:43",
			"tags" : ["那虹","办公室健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016002001.mp4",
			"content" : "《办公室女神养成记》是一档办公健身教学节目，让更多人能够在办公的同时也能健身，缓解办公室一族颈部、肩部的紧张，下面就跟着办公室健身女神一起运动吧。"
		},
		{
			"vid" : "2016002002",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016002b.jpg",
			"title" : "办公室女神养成记02",
			"subtitle" : "跟着那虹在办公室运动起来",
			"duration" : "01:57",
			"tags" : ["那虹","办公室健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016002002.mp4",
			"content" : "《办公室女神养成记》是一档办公健身教学节目，让更多人能够在办公的同时也能健身，缓解办公室一族颈部、肩部的紧张，下面就跟着办公室健身女神一起运动吧。"
		},
		{
			"vid" : "2016002003",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016002c.jpg",
			"title" : "办公室女神养成记03",
			"subtitle" : "洛希陪你做 再也找不到不减肥的理由了",
			"duration" : "02:39",
			"tags" : ["那虹","办公室健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016002003.mp4",
			"content" : "《办公室女神养成记》是一档办公健身教学节目，让更多人能够在办公的同时也能健身，缓解办公室一族颈部、肩部的紧张，下面就跟着办公室健身女神一起运动吧。"
		},
		{
			"vid" : "2016002004",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016002d.jpg",
			"title" : "那虹健身房宣传",
			"subtitle" : "女神的办公室娱乐",
			"duration" : "01:00",
			"tags" : ["那虹","美女","运动"],
			"production" : "夜动体育 x 龙熹山健身房",
			"sponsor" : "Nike，Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016002004.mp4",
			"content" : "演员那虹在健身房的常规训练，我们可以跟着她一起做瘦腿收腹运动哦。"
		}],
	"003" : [{
			"vid" : "2016003001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016003a.jpg",
			"title" : "丁梵居家瘦身系列01",
			"subtitle" : "谁说在家就不能好好运动瘦身的？",
			"duration" : "04:05",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016003001.mp4",
			"content" : "丁梵瘦身系列之居家健身，在家也能减肥瘦身。瘦身教主丁梵教你怎么在家里轻松做运动。"
		},
		{
			"vid" : "2016003002",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016003b.jpg",
			"title" : "丁梵居家瘦身系列02",
			"subtitle" : "谁说在家就不能好好运动瘦身的？",
			"duration" : "02:34",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Adidas",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016003002.mp4",
			"content" : "丁梵瘦身系列之居家健身，在家也能减肥瘦身。瘦身教主丁梵教你怎么在家里轻松做运动。"
		},
		{
			"vid" : "2016003003",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016003c.jpg",
			"title" : "丁梵居家瘦身系列03",
			"subtitle" : "谁说在家就不能好好运动瘦身的？",
			"duration" : "02:58",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 英诺创业中心",
			"sponsor" : "Nike，Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016003003.mp4",
			"content" : "丁梵瘦身系列之居家健身，在家也能减肥瘦身。瘦身教主丁梵教你怎么在家里轻松做运动。"
		}],
	"004" : [{
			"vid" : "2016004001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016004a.jpg",
			"title" : "丁梵亲子瑜伽课堂01",
			"subtitle" : "带着宝宝们一起做瑜伽，亲子又健康",
			"duration" : "03:14",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016004001.mp4",
			"content" : "亲子瑜伽是一种在欧美等国家流行起来的时尚母子瑜伽。适合儿童与家长共同参与的体位法和瑜伽游戏，一般适合0-12岁的儿童与家长一起练习，特别是7岁前，更是学瑜伽的好时机。所以我们特此聘请专业教练丁梵老师和她两岁的儿子一起为大家展示亲子瑜伽的魅力。"
		},
		{
			"vid" : "2016004002",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016004b.jpg",
			"title" : "丁梵亲子瑜伽课堂02",
			"subtitle" : "带着宝宝们一起做瑜伽，亲子又健康",
			"duration" : "03:46",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016004002.mp4",
			"content" : "亲子瑜伽是一种在欧美等国家流行起来的时尚母子瑜伽。适合儿童与家长共同参与的体位法和瑜伽游戏，一般适合0-12岁的儿童与家长一起练习，特别是7岁前，更是学瑜伽的好时机。所以我们特此聘请专业教练丁梵老师和她两岁的儿子一起为大家展示亲子瑜伽的魅力。"
		},
		{
			"vid" : "2016004003",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016004c.jpg",
			"title" : "丁梵亲子瑜伽课堂03",
			"subtitle" : "带着宝宝们一起做瑜伽，亲子又健康",
			"duration" : "03:32",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016004003.mp4",
			"content" : "亲子瑜伽是一种在欧美等国家流行起来的时尚母子瑜伽。适合儿童与家长共同参与的体位法和瑜伽游戏，一般适合0-12岁的儿童与家长一起练习，特别是7岁前，更是学瑜伽的好时机。所以我们特此聘请专业教练丁梵老师和她两岁的儿子一起为大家展示亲子瑜伽的魅力。"
		},
		{
			"vid" : "2016004004",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016004d.jpg",
			"title" : "丁梵亲子瑜伽课堂03",
			"subtitle" : "带着宝宝们一起做瑜伽，亲子又健康",
			"duration" : "03:56",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016004004.mp4",
			"content" : "亲子瑜伽是一种在欧美等国家流行起来的时尚母子瑜伽。适合儿童与家长共同参与的体位法和瑜伽游戏，一般适合0-12岁的儿童与家长一起练习，特别是7岁前，更是学瑜伽的好时机。所以我们特此聘请专业教练丁梵老师和她两岁的儿子一起为大家展示亲子瑜伽的魅力。"
		},
		{
			"vid" : "2016004005",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016004e.jpg",
			"title" : "丁梵亲子瑜伽课堂03",
			"subtitle" : "带着宝宝们一起做瑜伽，亲子又健康",
			"duration" : "04:04",
			"tags" : ["丁梵","居家健身","美女","运动"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016004005.mp4",
			"content" : "亲子瑜伽是一种在欧美等国家流行起来的时尚母子瑜伽。适合儿童与家长共同参与的体位法和瑜伽游戏，一般适合0-12岁的儿童与家长一起练习，特别是7岁前，更是学瑜伽的好时机。所以我们特此聘请专业教练丁梵老师和她两岁的儿子一起为大家展示亲子瑜伽的魅力。"
		}],
	"005" : [{
			"vid" : "2016005001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016005a.jpg",
			"title" : "都市美人鱼—小月月",
			"subtitle" : "跳水冠军化身美人鱼，带你游走在水底",
			"duration" : "03:32",
			"tags" : ["郑茹月","小月月","潜水运动","潜浮"],
			"production" : "夜动体育 x 索菲特健身",
			"sponsor" : "Fitti菲比，索菲特健身中心",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016005001.mp4",
			"content" : "郑茹月，跳水冠军化身美人鱼，带你游走在水底。看似简单的潜浮，在小月月看来都那么的娴熟~一起来看下她给我们演绎的水下芭蕾。"
	}],
	"006" : [{
			"vid" : "2016006001",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016006a.jpg",
			"title" : "跑如羚羊-女孩必學的跑步玩髮",
			"subtitle" : "NB ZOO RUN跑步教室",
			"duration" : "02:02",
			"tags" : ["跑步","夜跑","热身运动"],
			"production" : "New Balance",
			"sponsor" : "New Balance, Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016006001.mp4",
			"content" : "【NB ZOO RUN跑步教室#1】跑如羚羊-女孩必學的跑步玩'髮'，總是綁著一成不變的馬尾去跑步嗎?就讓甜心主播-簡懿佳示範給妳看，五種女孩必學的跑步玩'髮'妳最喜歡哪一個呢?歡迎大家在底下留言跟我們，也跟我們分享妳跑步時的髮型!!別忘了，9/25那天，用這些可愛的造型，一起來加入我們動物園路跑的行列吧!"
	},{
			"vid" : "2016006002",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016006b.jpg",
			"title" : "跑如脫兔-親子路跑必學5招",
			"subtitle" : "NB ZOO RUN跑步教室",
			"duration" : "02:00",
			"tags" : ["跑步","夜跑","热身运动"],
			"production" : "New Balance",
			"sponsor" : "New Balance, Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016006002.mp4",
			"content" : "爸爸媽媽喜歡跑步，想帶著小朋友一起享受跑步嗎? NB ZOO RUN跑步教室#2楊志祥老師要教爸爸媽媽親子路跑的小秘訣。【第一】-六分飽跑步沒煩惱；【第二招】-親子互動熱身添興趣；【第三招】-養成小朋友熱身的好習慣；【第四招】和第五招答案就在影片中。爸爸媽媽不要只抓寶，也要記得帶小朋友一起去跑跑喔!9/25一起來加入我們動物園路跑的行列吧!"
	},{
			"vid" : "2016006003",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016006c.jpg",
			"title" : "跑如潑猴-初階跑者必學5招",
			"subtitle" : "NB ZOO RUN跑步教室",
			"duration" : "01:48",
			"tags" : ["跑步","夜跑","热身运动"],
			"production" : "New Balance",
			"sponsor" : "New Balance, Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016006003.mp4",
			"content" : "剛開始挑戰路跑，動物園路跑4K是你可以選擇的入門的挑戰，但挑戰前先讓NB ZOO RUN跑步教室#3暖男鐵人楊志祥老師教你初階跑者五個小祕訣。【第一招】-跑前暖身很重要；【第二招】- .跑前這樣吃最聰明；【第三招】-穩定跑姿最省力：【第四招】-專注吐氣順暢跑；【第五招】-最後收操不鐵腿。9/25一起來加入我們動物園路跑的行列吧!"
	},{
			"vid" : "2016006004",
			"imgurl" : "http://olppdb3c8.bkt.clouddn.com/album2016006d.jpg",
			"title" : "跑如獵豹 五大必學密技",
			"subtitle" : "NB ZOO RUN跑步教室",
			"duration" : "01:47",
			"tags" : ["跑步","夜跑","热身运动"],
			"production" : "New Balance",
			"sponsor" : "New Balance, Yechtv",
			"source" : "http://olppdb3c8.bkt.clouddn.com/2016006004.mp4",
			"content" : "本周暖男鐵人楊志祥/Chih Hsiang YANG教練要教進階跑者者必學5招幫你10K破PB。1. 上坡跑步有訣竅；2. 下坡穩定別暴衝；3. 馬克操幫你加速 ；4. 滾輪按摩兼舒壓 ；5. 核心強化超重要。想要擺脫初階變成進階的跑者，一定要學起來喔!"
	}]
}
